POST http://localhost:5000/api/user/register
Content-Type: application/json

{
  "name" : "Bhuban",
  "email" : "bhuban@gmail.com",
  "password" : "bunny98689"
}

###
POST http://localhost:5000/api/user/login
Content-Type: application/json

{
  "email" : "bhuban@gmail.com",
  "password" : "bunny98689"
}

###
GET http://localhost:5000/api/user/getAll 

###
GET http://localhost:5000/api/user/get/6a21ab1e986ed1b3c0d54fc7
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhMjNmMTJhYTczNzUwMTNiNDIzMjhlOSIsImlhdCI6MTc4MTM2OTg4NywiZXhwIjoxNzgxNDU2Mjg3fQ.wveGo1qKypGfy8WwGQddtATRq04Aza2k0lvIV_pyFog


###
PATCH http://localhost:5000/api/user/update/6a21ab1e986ed1b3c0d54fc7
Content-Type: application/json

{
  "name" : "Bunny chy"
}

###
DELETE http://localhost:5000/api/user/delete/6a21ab1e986ed1b3c0d54fc7
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhMmQ4ZmI2NGI0OGViNjdlMjExNThmYyIsImlhdCI6MTc4MTM3MTc2MiwiZXhwIjoxNzgxNDU4MTYyfQ.2TctxJ7-erR97OW4wc2L9bjI_1GdJrqUHzSz9dljGqI

### 
