POST http://localhost:5000/api/user/register
Content-Type: application/json

{
  "name" : "Samir",
  "email" : "samir@gmail.com",
  "password" : "bunny98689"
}

###
POST http://localhost:5000/api/user/login
Content-Type: application/json

{
  "email" : "samir@gmail.com",
  "password" : "bunny98689"
}

###
GET http://localhost:5000/api/user/getAll 

###
GET http://localhost:5000/api/user/get/6a21a80c25e5f7c424755b98